from matplotlib import rcParams

rcParams['font.family']         = 'DejaVu Sans'
rcParams['font.weight']         = 'bold'  
rcParams['font.size']           = 15
rcParams['figure.figsize']      = [15, 8]
rcParams['figure.titlesize']    = 20
rcParams['figure.titleweight']  = 'bold'
rcParams['axes.titlesize']      = 15
rcParams['axes.labelsize']      = 15
rcParams['axes.titleweight']    = 'bold' 
rcParams['axes.labelweight']    = 'bold'
rcParams['axes.linewidth']      = 2
rcParams['xtick.top']           = True
rcParams['ytick.right']         = True
rcParams['xtick.minor.visible'] = True
rcParams['ytick.minor.visible'] = True
rcParams['xtick.labelsize']     = 12  
rcParams['ytick.labelsize']     = 12  
rcParams['xtick.direction']     = 'inout'
rcParams['ytick.direction']     = 'inout'
rcParams['xtick.major.width']   = 2
rcParams['ytick.major.width']   = 2
rcParams['xtick.minor.width']   = 1.5
rcParams['ytick.minor.width']   = 1.5
rcParams['xtick.major.size']    = 6
rcParams['ytick.major.size']    = 6
rcParams['xtick.minor.size']    = 4
rcParams['ytick.minor.size']    = 4
rcParams['savefig.bbox']        = 'tight'
rcParams['savefig.dpi']         = 200